# -*- coding: utf-8 -*-
"""BulychevaEV_Itogovoe zadanie_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZ5f2SmOAo54cjdoKbMuFlaW8TILvAT9
"""

!pip install requests pandas matplotlib seaborn

import random
import string
import json
from datetime import datetime, timedelta, timezone

# Генерация случайных значений из закрытых списков для IP, протокола, нагрузки, ID правил, уровня серьезности, отметки угрозы, категории угрозы
def random_ip():
    return '.'.join(map(str, (random.randint(0, 255) for _ in range(4))))

def random_protocol():
    protocols = ['TCP', 'UDP', 'HTTP', 'FTP', 'SSH', 'DNS']
    return random.choice(protocols)

def random_payload(size=10):
    letters = string.ascii_letters + string.digits
    return ''.join(random.choice(letters) for i in range(size))

def random_rule_id():
    return random.randint(1000, 9999)

def random_severity():
    severities = ['INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
    return random.choice(severities)

def random_signature():
    signatures = [
        'Possible SQL injection attempt',
        'Potential XSS attack detected',
        'Malformed packet detected',
        'Suspicious port scan activity',
        'DDoS traffic detected',
        'Unauthorised access attempt',
        'Malware infection detected',
        'Data exfiltration attempt'
    ]
    return random.choice(signatures)

def random_category():
    categories = ['Attack', 'Network Activity', 'Anomaly', 'Malware', 'Policy Violation']
    return random.choice(categories)

# Генерируем 100 логов
def generate_suricata_logs(num_entries=100):
    start_time = datetime.now(timezone.utc) - timedelta(hours=1)
    logs = []

    for _ in range(num_entries):
        timestamp = start_time.strftime('%Y-%m-%dT%H:%M:%SZ')
        event_type = random.choice(['alert', 'drop'])
        source_ip = random_ip()
        destination_ip = random_ip()
        protocol = random_protocol()
        payload = random_payload()
        rule_id = random_rule_id()
        severity = random_severity()
        signature = random_signature()
        category = random_category()
        destination_port = random.randint(1024, 65535)

        log_entry = {
            "timestamp": timestamp,
            "event_type": event_type,
            "source_ip": source_ip,
            "destination_ip": destination_ip,
            "protocol": protocol,
            "payload": payload,
            "rule_id": rule_id,
            "severity": severity,
            "signature": signature,
            "category": category,
            "destination_port": destination_port
        }

        logs.append(log_entry)
        start_time += timedelta(seconds=random.randint(1, 10))

    return logs

# Записываем логи в файл suricata.log (он сгенерирован и приложен к ДЗ)
def save_logs_to_file(logs, filename='suricata.log'):
    with open(filename, 'w') as file:
        for log in logs:
            file.write(json.dumps(log) + "\n")

# Генерация и сохранение логов
logs = generate_suricata_logs(100)
save_logs_to_file(logs)

print(f"Сгенерировано и сохранено {len(logs)} записей в файл 'suricata.log'")

# Создаем файл со сгенерированными IP-адресами для анализа с помощью VirusTotal
import random

# Задаем количество "100" IP-адресов для генерации
num_ips = 100

# Выполняем генерацию случайных IP-адресов
random_ips = []
for _ in range(num_ips):
    ip = ".".join(str(random.randint(0, 255)) for _ in range(4))
    random_ips.append(ip)

# Записываю IP-адреса в файл
filename = 'random_ips.txt'
with open(filename, 'w') as file:
    for ip in random_ips:
        file.write(ip + '\n')

print(f"{len(random_ips)} случайных IP-адресов было создано и записано в файл '{filename}'.")

import random
import string
import json
import requests
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta, timezone

# API Key для VirusTotal
VT_API_KEY = 'dcca36ff37e6d8500be852581205482b7ee67821653805ee404b3fee05030fa6'

# Функция для чтения логов Suricata
def load_suricata_logs(file_path='suricata.log'):
    with open(file_path, 'r') as file:
        logs = [json.loads(line.strip()) for line in file]
    return logs

# Функция для анализа логов через API VirusTotal
def analyze_with_virustotal(ip_address):
    headers = {'x-apikey': VT_API_KEY}
    response = requests.get(f'https://www.virustotal.com/api/v3/ip_addresses/{ip_address}', headers=headers)
    if response.status_code == 200:
        return response.json()
    else:
        return None

# Функция для анализа подозрительности IP из файла random_ips.txt
def analyze_random_ips(file_path='random_ips.txt'):
    with open(file_path, 'r') as file:
        ips = file.read().splitlines()
    results = []
    for ip in ips:
        analysis_result = analyze_with_virustotal(ip)
        if analysis_result:
            threat_level = analysis_result['data']['attributes']['last_analysis_stats']['malicious']
            results.append({'IP': ip, 'Threat Level': threat_level})
    return results

# Функция для имитации отправки уведомления в Telegram, токен и ID замещены фиктивными значениями
def send_telegram_notification(message_text):
    bot_token = 'FAKE_BOT_TOKEN'
    chat_id = 'FAKE_CHAT_ID'
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    params = {'chat_id': chat_id, 'text': message_text}
    # Вместо реального запроса к Telegram делаем имитацию отправки
    print(f"! Имитация отправки сообщения в Telegram:\n{message_text}\n")

# Главная функция для выполнения анализа и формирования отчёта
def main():
    # Загружаем логи Suricata
    suricata_logs = load_suricata_logs()

    # Анализируем IP-адреса из файла random_ips.txt
    ip_analysis_results = analyze_random_ips()

    # Формируем DataFrame для удобной обработки данных
    df = pd.DataFrame(ip_analysis_results)

    # Выводим подозрительные IP-адреса
    suspicious_ips = df[df['Threat Level'] > 0]['IP'].values.tolist()
    if suspicious_ips:
        print(f"\n! Найдены подозрительные IP-адреса: {', '.join(suspicious_ips)}\n")
        # Имитация отправки уведомления в Telegram
        notification_message = f"В результате анализа обнаружены следующие подозрительные IP-адреса:\n\n{suspicious_ips}"
        send_telegram_notification(notification_message)
    else:
        print("\n! Угрозы не найдены.\n")

    # Визуализация топ-5 наиболее подозрительных IP
    df_sorted = df.sort_values(by=['Threat Level'], ascending=False).head(5)
    plt.figure(figsize=(10, 6))
    plt.barh(df_sorted['IP'], df_sorted['Threat Level'], color='skyblue')
    plt.xlabel('Уровень угрозы')
    plt.ylabel('IP-адрес')
    plt.title('Топ-5 наиболее подозрительных IP-адресов')
    plt.gca().invert_yaxis()
    plt.savefig('top_suspicious_ips.png')
    plt.show()

    # Сохраняем результаты анализа в CSV-файл
    df.to_csv('analysis_results.csv', index=False)

# Выполняем главный скрипт
if __name__ == '__main__':
    main()